version: '3.8'

services:
  pgvector_demo_local:
    image: ankane/pgvector
    container_name: pgvector_demo_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: vector_db
    ports:
      - "5432:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d  # Mount initialization scripts
    networks:
      - rag_network

  rag_app:
    build: .
    container_name: rag_app
    environment:
      - DB_HOST=pgvector_demo_local  # Use the PostgreSQL container name
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - GROQ_API_KEY=${GROQ_API_KEY}
    ports:
      - "8501:8501"
    depends_on:
      - pgvector_demo_local  # Ensure the PostgreSQL container starts first
    networks:
      - rag_network

volumes:
  pgvector_data:

networks:
  rag_network:
    driver: bridge